# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# extra
from random import randint
import main
numero_resposta = None
corretas = 0
erradas = 0
numero_perguntas = 1

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.R1 = QtWidgets.QPushButton(self.centralwidget)
        self.R1.setGeometry(QtCore.QRect(30, 150, 131, 81))
        self.R1.setObjectName("R1")
        self.R4 = QtWidgets.QPushButton(self.centralwidget)
        self.R4.setGeometry(QtCore.QRect(480, 150, 131, 81))
        self.R4.setObjectName("R4")
        self.R5 = QtWidgets.QPushButton(self.centralwidget)
        self.R5.setGeometry(QtCore.QRect(630, 150, 131, 81))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.R5.setFont(font)
        self.R5.setAcceptDrops(False)
        self.R5.setObjectName("R5")
        self.R2 = QtWidgets.QPushButton(self.centralwidget)
        self.R2.setGeometry(QtCore.QRect(180, 150, 131, 81))
        self.R2.setObjectName("R2")
        self.R3 = QtWidgets.QPushButton(self.centralwidget)
        self.R3.setGeometry(QtCore.QRect(330, 150, 131, 81))
        self.R3.setObjectName("R3")
        self.corpo_pergunta = QtWidgets.QTextBrowser(self.centralwidget)
        self.corpo_pergunta.setGeometry(QtCore.QRect(30, 60, 731, 71))
        self.corpo_pergunta.setObjectName("corpo_pergunta")
        self.titulo_pergunta = QtWidgets.QLabel(self.centralwidget)
        self.titulo_pergunta.setGeometry(QtCore.QRect(30, 10, 731, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.titulo_pergunta.setFont(font)
        self.titulo_pergunta.setObjectName("titulo_pergunta")
        self.avacar = QtWidgets.QPushButton(self.centralwidget)
        self.avacar.setGeometry(QtCore.QRect(30, 250, 731, 41))
        self.avacar.setObjectName("avacar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 310, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.corretas = QtWidgets.QLabel(self.centralwidget)
        self.corretas.setGeometry(QtCore.QRect(120, 410, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.corretas.setFont(font)
        self.corretas.setObjectName("corretas")
        self.erradas = QtWidgets.QLabel(self.centralwidget)
        self.erradas.setGeometry(QtCore.QRect(470, 410, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.erradas.setFont(font)
        self.erradas.setObjectName("erradas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menumenu = QtWidgets.QMenu(self.menubar)
        self.menumenu.setMinimumSize(QtCore.QSize(0, 0))
        self.menumenu.setObjectName("menumenu")
        self.menuedit = QtWidgets.QMenu(self.menubar)
        self.menuedit.setObjectName("menuedit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionnovo = QtWidgets.QAction(MainWindow)
        self.actionnovo.setObjectName("actionnovo")
        self.actionsalvar = QtWidgets.QAction(MainWindow)
        self.actionsalvar.setObjectName("actionsalvar")
        self.actionabrir = QtWidgets.QAction(MainWindow)
        self.actionabrir.setObjectName("actionabrir")
        self.actionclaro = QtWidgets.QAction(MainWindow)
        self.actionclaro.setObjectName("actionclaro")
        self.actionescuro = QtWidgets.QAction(MainWindow)
        self.actionescuro.setObjectName("actionescuro")
        self.menumenu.addAction(self.actionnovo)
        self.menumenu.addAction(self.actionsalvar)
        self.menumenu.addAction(self.actionabrir)
        self.menumenu.addSeparator()
        self.menuedit.addAction(self.actionclaro)
        self.menuedit.addAction(self.actionescuro)
        self.menubar.addAction(self.menumenu.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())
        self.R1.clicked.connect(self.Respondeu, 1)
        self.R2.clicked.connect(self.Respondeu, 2)
        self.R3.clicked.connect(self.Respondeu, 3)
        self.R4.clicked.connect(self.Respondeu, 4)
        self.R5.clicked.connect(self.Respondeu, 5)
        self.avacar.clicked.connect(self.proxima_pergunta)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "primeira tela"))
        self.R1.setText(_translate("MainWindow", "trocar imagens"))
        self.R4.setText(_translate("MainWindow", "trocar texto"))
        self.R5.setText(_translate("MainWindow", "nenhuma"))
        self.R2.setText(_translate("MainWindow", "PushButton"))
        self.R3.setText(_translate("MainWindow", "PushButton"))
        self.titulo_pergunta.setText(_translate("MainWindow", "TextLabel"))
        self.avacar.setText(_translate("MainWindow", "avançar"))
        self.label.setText(_translate("MainWindow", "resultados:"))
        self.corretas.setText(_translate("MainWindow", "corretas: __"))
        self.erradas.setText(_translate("MainWindow", "erradas: __"))
        self.menumenu.setTitle(_translate("MainWindow", "file"))
        self.menuedit.setTitle(_translate("MainWindow", "edit"))
        self.actionnovo.setText(_translate("MainWindow", "novo"))
        self.actionsalvar.setText(_translate("MainWindow", "salvar"))
        self.actionabrir.setText(_translate("MainWindow", "abrir"))
        self.actionclaro.setText(_translate("MainWindow", "claro"))
        self.actionescuro.setText(_translate("MainWindow", "escuro"))

        #extra
        self.botoes_resposta = [self.R1, self.R2, self.R3, self.R4, self.R5]
        self.montar_pergunta()

    def proxima_pergunta(self):
        global numero_perguntas
        numero_perguntas += 1
        self.montar_pergunta()
        for i in self.botoes_resposta:
            i.setStyleSheet('QPushButton {background-color:#FFFFFF;}')


    def Respondeu(self, value):
        global numero_resposta, corretas, erradas

        for i in range(len(self.botoes_resposta)):
            if numero_resposta == (i+1):
                self.botoes_resposta[i].setStyleSheet('QPushButton {background-color:#00FF00;}')
            else:
                self.botoes_resposta[i].setStyleSheet('QPushButton {background-color:#FF0000;}')

        if value == numero_resposta:
            corretas += 1
        else:
            erradas += 1

    def montar_pergunta(self):

        global numero_resposta
        pergunta_formada = main.formar_pergunta()
        self.titulo_pergunta.setText(pergunta_formada[0])
        self.corpo_pergunta.setText(pergunta_formada[1])
        posicionamento = randint(1, 5)

        if posicionamento == 5:
            numero_resposta = 5
            for i in range(len(self.botoes_resposta) - 1):
                self.botoes_resposta[i].setText(pergunta_formada[3][i])

        elif posicionamento == 4:
            numero_resposta = 4
            for i in range(len(self.botoes_resposta) - 1):
                if i == 3:
                    self.botoes_resposta[i].setText(pergunta_formada[2])
                else:
                    self.botoes_resposta[i].setText(pergunta_formada[3][i])

        elif posicionamento == 3:
            numero_resposta = 3
            for i in range(len(self.botoes_resposta) - 1):
                if i == 2:
                    self.botoes_resposta[i].setText(pergunta_formada[2])
                else:
                    self.botoes_resposta[i].setText(pergunta_formada[3][i])

        elif posicionamento == 2:
            numero_resposta = 2
            for i in range(len(self.botoes_resposta) - 1):
                if i == 1:
                    self.botoes_resposta[i].setText(pergunta_formada[2])
                else:
                    self.botoes_resposta[i].setText(pergunta_formada[3][i])

        else:
            numero_resposta = 1
            for i in range(len(self.botoes_resposta) - 1):
                if i == 0:
                    self.botoes_resposta[i].setText(pergunta_formada[2])
                else:
                    self.botoes_resposta[i].setText(pergunta_formada[3][i])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
